name: deadtime
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter

  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  http: ^1.3.0
  wifi_iot: ^0.3.19+1
  cloud_firestore: ^5.6.2
  firebase_database: ^11.3.2
  intl: 0.19.0
  esptouch_flutter: ^1.0.0
  permission_handler: ^11.3.1
  esp_smartconfig: ^2.0.4
  wifi_info_plugin_plus: ^2.0.2
  cupertino_icons: ^1.0.8
  firebase_messaging: ^15.2.2
  flutter_local_notifications: ^18.0.1
  googleapis_auth: ^1.6.0
  dart_jsonwebtoken: ^2.17.0
  googleapis: ^13.2.0
  firebase_analytics: ^11.4.3
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  flutter_background_service_ios: ^5.0.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^5.0.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo_foreground.png"
  adaptive_icon_background: "#ffffff"
# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true


  assets:
    - assets/logo_removebg2.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

